### PR TITLE
Update landing page with link to cloud sign up page

### PR DESCRIPTION
**Pull request by TeddyCr**
remove https://share.hsforms.com/1fstvMCeZRZKTYA4nG1VTPgcq0j9 to point to https://cloud.getcollate.io

Screenshot 2022-10-14 at 8 13 00 PM

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
Hello @TeddyCr, Any reason why we are removing the star us CTA?
Earlier we had this
image

And with this PR changes we have something like this

image

**Comment by Sachin-chaurasiya** [comment]
We will make changes on the landing page and show signup for the cloud like this.
image

**Comment by TeddyCr** [comment]
Ah yes that button would need to be fixed. The start us button is at the top to leave room for the try for free button.

It was more a suggested layout -- wasn't aware of the banner design in the work. 

Would it be interesting/possible to foam AB test to see which design will drive more conversions?

**Comment by Sachin-chaurasiya** [comment]
> Ah yes that button would need to be fixed. The start us button is at the top to leave room for the try for free button.
> 
> It was more a suggested layout -- wasn't aware of the banner design in the work.
> 
> Would it be interesting/possible to foam AB test to see which design will drive more conversions?

Sure we can discuss this.

**Comment by harshach** [comment]
@Sachin-chaurasiya can we land this quickly?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can we land this quickly?

Sure @harshach

**Comment by Sachin-chaurasiya** [comment]
@harshach, Changes are done, please review.

**Review by harshach — APPROVED** [review]

**Pull request merged**
