### PR TITLE
Add script file for piwik

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
As part of this https://github.com/open-metadata/openmetadata-site/pull/45 PR we have added Piwik tracking, So this PR is for removing duplication and creating a single script file for Piwik code and linking them to both HTML files.
cc : @TeddyCr

### CODE REVIEW

**Review by pmbrull — APPROVED** [review]
@Sachin-chaurasiya this looks awesome. I am wondering if we could have something similar for the docs repo as well

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya this looks awesome. I am wondering if we could have something similar for the docs repo as well

Thanks, @pmbrull , Sure we can sync up for that,

**Comment by TeddyCr** [comment]
@pmbrull @Sachin-chaurasiya just saw this was merged. Wondering if you saw my comment regarding the location of the script tag?

**Comment by Sachin-chaurasiya** [comment]
> @pmbrull @Sachin-chaurasiya just saw this was merged. Wondering if you saw my comment regarding the location of the script tag?

Hey @TeddyCr , Can you provide more context here?

**Comment by TeddyCr** [comment]
They recommend putting the script right after the opening body tag -- I am guessing it has to do with the way elements are loaded on the page and making sure this gets fired as soon as possible for better tracking.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya They recommend putting the script right after the opening body tag -- I am guessing it has to do with the way elements are loaded on the page and making sure this gets fired as soon as possible for better tracking.

@TeddyCr , Okay got it. 
PR for the same https://github.com/open-metadata/openmetadata-site/pull/47

**Pull request merged**
